name: Continuous Integration and Deployment of B2AI Peds Protocol

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set Environment Variables
      run: |
        echo "PROTOCOL_COMBINED_SLUG=peds-protocol-combined" >> $GITHUB_ENV
        echo "PROTOCOL_QUESTIONNAIRES_SLUG=peds-protocol-questionnaires" >> $GITHUB_ENV
    
    - name: Echo Environment Variables
      run: |
        echo "PROTOCOL_COMBINED_SLUG is set to $PROTOCOL_COMBINED_SLUG"
        echo "PROTOCOL_QUESTIONNAIRES_SLUG is set to $PROTOCOL_QUESTIONNAIRES_SLUG"
    
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetches the entire history for comprehensive CI checks

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.x' # Updated to a more recent LTS version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Updated to Python 3.10

    - name: Install system dependencies
      run: sudo apt-get install jq

    - name: Read Checksum from config.env
      run: |
        echo "Reading checksum..."
        CHECKSUM=$(cat config.env | grep REPROSCHEMA_UI_CHECKSUM | cut -d '=' -f2)
        echo "LATEST_COMMIT_HASH=${CHECKSUM}" >> $GITHUB_ENV

    - name: Install Node dependencies and validate JSON
      run: |
        npm install -g jsonlint
        # Validate JSON files for both protocols
        find . -name "*.json" -path "./peds-protocol-*" | xargs -I {} jsonlint -q {}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install reproschema requests_cache pre-commit
    
    - name: Test with pyshacl
      run: |
        # Validate both protocol schemas
        reproschema -l DEBUG validate ${PROTOCOL_COMBINED_SLUG}/activities
        reproschema -l DEBUG validate ${PROTOCOL_COMBINED_SLUG}/peds-protocol/peds-protocol
        reproschema -l DEBUG validate ${PROTOCOL_QUESTIONNAIRES_SLUG}/activities
        reproschema -l DEBUG validate ${PROTOCOL_QUESTIONNAIRES_SLUG}/peds-protocol/peds-protocol

    - name: Build Combined Protocol UI
      run: |
        # Download and setup UI for combined protocol
        curl -O -sSL https://github.com/ReproNim/reproschema-ui/archive/${LATEST_COMMIT_HASH}.zip
        unzip ${LATEST_COMMIT_HASH}.zip
        mv reproschema-ui-* ui-combined
        cd ui-combined
        cp -r ../${PROTOCOL_COMBINED_SLUG}/ui-changes/. .
        # Modify the title in index.html
        sed -i 's/<title>.*<\/title>/<title>B2AI Peds Protocol - Combined<\/title>/' public/index.html
        npm install
        npm run build
        cd ..

    - name: Build Questionnaires Protocol UI
      run: |
        # Download and setup UI for questionnaires protocol
        curl -O -sSL https://github.com/ReproNim/reproschema-ui/archive/${LATEST_COMMIT_HASH}.zip
        unzip ${LATEST_COMMIT_HASH}.zip
        mv reproschema-ui-* ui-questionnaires
        cd ui-questionnaires
        cp -r ../${PROTOCOL_QUESTIONNAIRES_SLUG}/ui-changes/. .
        # Modify the title in index.html
        sed -i 's/<title>.*<\/title>/<title>B2AI Peds Protocol - Questionnaires<\/title>/' public/index.html
        npm install
        npm run build
        cd ..

    - name: Prepare deployment folder
      run: |
        # Create deployment folder structure
        mkdir -p deploy
        mkdir -p deploy/combined
        mkdir -p deploy/questionnaires
        
        # Copy built UIs to respective folders
        cp -r ui-combined/dist/* deploy/combined/
        cp -r ui-questionnaires/dist/* deploy/questionnaires/
        
        # Create root index.html to redirect or show options
        cat > deploy/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>B2AI Pediatric Protocol</title>
            <style>
                body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
                .protocol-link { display: block; padding: 20px; margin: 20px 0; background: #f5f5f5; border-radius: 8px; text-decoration: none; color: #333; }
                .protocol-link:hover { background: #e9e9e9; }
                h1 { text-align: center; color: #2c3e50; }
                h2 { color: #34495e; }
            </style>
        </head>
        <body>
            <h1>B2AI Pediatric Protocol</h1>
            <p>Choose which protocol version you want to access:</p>
            
            <a href="./combined/" class="protocol-link">
                <h2>🔬 Combined Protocol</h2>
                <p>Complete protocol including speech tasks and assessments</p>
            </a>
            
            <a href="./questionnaires/" class="protocol-link">
                <h2>📝 Questionnaires Only</h2>
                <p>Questionnaire-based assessments and forms</p>
            </a>
        </body>
        </html>
        EOF
        
        # Add .nojekyll to prevent Jekyll processing
        touch deploy/.nojekyll

    - name: Deploy to GitHub Pages 🚀
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: deploy